# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\"\x06\n\x04Void\"\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x16\n\x05State\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x42\n\x05Light\x12\x1c\n\x06Toggle\x12\x05.Void\x1a\t.Response\"\x00\x12\x1b\n\x08GetState\x12\x05.Void\x1a\x06.State\"\x00\x32W\n\x0e\x41irConditioner\x12(\n\x11\x43hangeTemperature\x12\x06.State\x1a\t.Response\"\x00\x12\x1b\n\x08GetState\x12\x05.Void\x1a\x06.State\"\x00\x32o\n\x0e\x46ireSuppressor\x12\x1e\n\x08\x41\x63tivate\x12\x05.Void\x1a\t.Response\"\x00\x12 \n\nDeactivate\x12\x05.Void\x1a\t.Response\"\x00\x12\x1b\n\x08GetState\x12\x05.Void\x1a\x06.State\"\x00\x62\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['Void']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_STATE = DESCRIPTOR.message_types_by_name['State']
Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:State)
  })
_sym_db.RegisterMessage(State)

_LIGHT = DESCRIPTOR.services_by_name['Light']
_AIRCONDITIONER = DESCRIPTOR.services_by_name['AirConditioner']
_FIRESUPPRESSOR = DESCRIPTOR.services_by_name['FireSuppressor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=20
  _VOID._serialized_end=26
  _RESPONSE._serialized_start=28
  _RESPONSE._serialized_end=55
  _STATE._serialized_start=57
  _STATE._serialized_end=79
  _LIGHT._serialized_start=81
  _LIGHT._serialized_end=147
  _AIRCONDITIONER._serialized_start=149
  _AIRCONDITIONER._serialized_end=236
  _FIRESUPPRESSOR._serialized_start=238
  _FIRESUPPRESSOR._serialized_end=349
# @@protoc_insertion_point(module_scope)
